[tool.poetry]
name = "quantum-surrogate-project"
version = "0.1.0"
description = ""
authors = ["lc3267 <melvin.strobl@kit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
ipykernel = "^6.27.1"
pennylane = "^0.35.1"
matplotlib = "^3.8.2"
plotly = "^5.18.0"
pandas = "^2.1.4"
nbformat = "^5.9.2"
ipywidgets = "^8.1.1"
dash = "^2.16.1"
dash-bootstrap-components = "^1.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
